language: java
jdk:
  -openjdk8
deploy:
  provider: heroku
  api_key:
     secure: "gG2otTM/f6jvgDb6mG/26TorxaId3LP7ofyXdJwZEtbU2HfejFKCFQQmjUC2r2ULxvnPkJavLRj+WTelDs0bt1/Iu8MpjK+OQixCjVyBdVQdLozqgpUBzYV2GXJsD/CGFdJ3Dfprdw/jrE+MmrXQwwchscwwJ3bbsHPU4Z8yW7aTqLi5mU37HBtro0jAHqIr1JAwcNfgjFFNq+VYZTgbGuS8GGgaNO76ABsb5jJ1UEJndJ6dEhuKGXPB0IoftiL+eQTHwb3fb/0AMs8nupv+fgMNxbK+dFPHUdCUkMhZVuz4le9MWPRkUNx6WHyfbwOmhGGdTTqRARiYItQKB9bOL9+M79QzdRoKBBGQ/d3m2vsN1g8wxEO6gZ7xtP2hWiL6RC3QVeXR7B6v0q1ESOWlSwnE565BF5tK2M+ox54W2RHVTJHt5ahU0DnmE2cQpyjFTQGWtswt1dezR3WnlY0hECs9+hb6OYdNqdvtdtcLhD20NWqNUPGfk49NoxNqPQXNASzujlLv1/A0zmUcEHFOQy/OkOymvpqPWRdEjl5nLBIbicnTMlEfJ+/SyC915c0Kse9TPO+sHHKlJHZ15KgvU3dRxqoG8TGO//xnv3KC4PYXQCAS48qWAM2RP4KDbSyrn1Q+PBSKrDt3iSITZci8PIEsan0H/dIRy/JsQvkpfuI="
  app: curriculum-grid-dev
  on:
    all_branches: true