server:
  port: 8081
  servlet:
    contextPath: /
spring:
  datasource:
    driverClassName: org.postgresql.Driver

    url: ${DATABASE_URL}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
