logging:
  level:
    org:
      springframework:
        web: INFO
server:
  servlet:
    contextPath: /
spring:
  datasource:
    driverClassName: org.postgresql.Driver

    url: ${DATABASE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update    show-sql: true
