logging:
  level:
    org:
      springframework:
        web: INFO
server:
  servlet:
    contextPath: /
spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect    show-sql: true
  